Improve publish test readability (#8)
When adding features to the publish function, the errors raised
by the current implementation makes it hard to troubleshoot.

```
UploadDashboard(*client.Dashboard)
			0: &client.Dashboard{UID:"", Title:"", FolderUID:"common-folder-uid", Dashboard:map[string]interface {}{"folderUid":"common-folder-uid", "tags":[]interface {}{"tag1", "tag2"}, "title":"Common Dashboard", "uid":"common-dash-uid-suffix"}, Meta:(*models.DashboardMeta)(nil)}

	The closest call I have is:

	UploadDashboard(mock.argumentMatcher)
			0: mock.argumentMatcher{fn:reflect.Value{typ_:(*abi.Type)(0x100df5a80), ptr:(unsafe.Pointer)(0x100f314d8), flag:0x13}}

```

This is particularly true because in this test, we use a mock function to assert on the test expected behaviour.

This commit proposes to change this approach and instead use an assert at the end of the test.
This is expected to provide better error messages to debug tests and implementations

Resulting assertions:

```console
                Error:          Not equal:
                                expected: map[string]*client.Dashboard{"common-dash-uid":(*client.Dashboard)(0x140003be4b0), "custom-dash-uid":(*client.Dashboard)(0x140003be500)}
                                actual  : map[string]*client.Dashboard{"common-dash-uid":(*client.Dashboard)(0x140003be280), "custom-dash-uid":(*client.Dashboard)(0x140003be140)}

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -2,3 +2,3 @@
                                  (string) (len=15) "common-dash-uid": (*client.Dashboard)({
                                -  UID: (string) "",
                                +  UID: (string) (len=15) "common-dash-uid",
                                   Title: (string) "",
                                @@ -13,3 +13,3 @@
                                  (string) (len=15) "custom-dash-uid": (*client.Dashboard)({
                                -  UID: (string) "",
                                +  UID: (string) (len=15) "custom-dash-uid",
                                   Title: (string) "",
```

Change-Id: I9ce8260c2f50904e5ca96c3026d5082fcf24bfa0